### ISSUE TITLE
Support Zod

### ISSUE THREAD

**Issue by ilteoood** [nearform/openapi-transformer-toolkit#5]
It would be awesome if, together with json schemas and ts types, we could also support zod, maybe using something like: https://github.com/StefanTerdell/json-schema-to-zod

**Comment by simoneb** [comment]
@karl-power have we come to a conclusion on this?

**Comment by karl-power** [comment]
I think can close this as as we cannot use the above linked library due to lack of full support for overlap with Zod, and may not actually be able to support it fully at all if what the author says is true. 

Also, the view of @toomuchdesign is that adding support for specific libraries adds more cons than pros.

**Comment by simoneb** [comment]
Agreed
